version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
      - "33060:33060"
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
    volumes:
      - "./MySQL/conf.d:/etc/mysql/conf.d"
      - "./MySQL/data:/var/lib/mysql"
    networks:
      localServer-bridge:
        aliases:
        - mysql

  emqx:
    image: emqx:latest
    container_name: emqx
    restart: always
    volumes:
      - ./EMQX/data:/opt/emqx/data
      - ./EMQX/etc:/opt/emqx/opt
      - ./EMQX/log:/opt/emqx/log
    ports:
      - "1883:1883"
      - "18083:18083"
    networks:
      localServer-bridge:
        aliases:
        - emqx

  gogs:
    image: gogs/gogs:0.12
    container_name: gogs
    restart: always
    volumes:
      - ./gogs/data:/data
    ports:
      - "3000:3000"
    networks:
      localServer-bridge:
        aliases:
        - gogs

  kasmweb:
    image: kasmweb/ubuntu-bionic-desktop:1.10.0-rolling
    container_name: kasmweb
    restart: always
    ports:
      - "6901:6901"
    environment:
      - VNC_PW=0697
    networks:
      localServer-bridge:
        aliases:
        - kasm
    shm_size: 512m

networks:
  localServer-bridge:
    driver: bridge
